#!/bin/bash

TEST_PATH=$(dirname $0)
RESULT_PATH=$(pwd)
hostinfo | grep Darwin && IN_OSX=1 || IN_OSX=0

REPS=100

echo "Local test executing"

${SSH_EXEC} "sudo shutdown linux-guest-1"
sleep 5
${SSH_EXEC} "sudo destroy linux-guest-1"
sleep 1
${SSH_EXEC} "sudo xl list"

# use ping to get remote IP, works for mdns + dns
REMOTE_IP=$(ping -c1 $REMOTE_HOST | head -n1 | cut -f2 -d"(" | cut -f1 -d")")
echo "remote ip is $REMOTE_IP"

LOCAL_IP=$(${SSH_EXEC} "lastlog | grep mirage | cut -b27-42")
echo "local ip is $LOCAL_IP"

if [ $IN_OSX == 1 ]; then
	# this only works in osx, see ip route get x.x.x.x in linux
	IF=$(route -n get $REMOTE_IP | grep interface | cut -d":" -f2 | tr -d " ")
	TCPDUMP=tcpdump
else # linux
	IF=$(ip route get 10.0.1.140 | grep dev | cut -f 3 -d " " | tr -d ' ')
	TCPDUMP="sudo tcpdump"
fi

echo "using interface $IF"

for f in $(seq 1 $REPS); do
    echo "Repetition $f of $REPS"
    $TCPDUMP -ni $IF -s 1024 -w $RESULT_PATH/cold_dump_${f}.pcap -U \
        "(port 22) and 
         ((src $LINUX_GUEST_IP1 and dst $LOCAL_IP) or
         (src $LOCAL_IP and dst $LINUX_GUEST_IP1))" &
    TCPDUMP_PID=$!

    sleep 1 # give tcpdump time to start

    ${SSH_EXEC} "sudo xl create $REMOTE_TEST_ROOT_PATH/linux-guest-1.conf"
    sudo hping3 -S -p 22 $LINUX_GUEST_IP1 | while read g; do if [[ $g =~ "flags=SA" ]]; then echo "Done" $g; sudo pkill hping3; else echo $g; fi; done ; 

    sudo kill $TCPDUMP_PID

    echo "xl status:"
    ${SSH_EXEC} "sudo xl list"

    echo "Destroying unikernel..."
    ${SSH_EXEC} "sudo xl shutdown linux-guest-1" #try shutdown first
    sleep 1
    ${SSH_EXEC} "sudo xl destroy linux-guest-1" #destroy just in case

    echo "Libvirt status:"
    ${SSH_EXEC} "sudo xl list"
done

${SSH_EXEC} "sudo xl shutdown linux-guest-1" #try shutdown first
sleep 1
${SSH_EXEC} "sudo xl destroy linux-guest-1" #destroy just in case
echo "Waiting 60 seconds..."
sleep 60
kill_remote

