#!/bin/bash

TEST_PATH=$(dirname $0)
RESULT_PATH=$(pwd)

MIRAGE_VER=2.2
echo "This test requires Mirage $MIRAGE_VER"
opam list mirage | grep $MIRAGE_VER && echo "Mirage $MIRAGE_VER found" || exit -1

#echo "This test requires tcpip to be pinned to https://github.com/samoht/mirage-tcpip#fast-start"
#opam info tcpip | grep upstream | grep samoht || exit -1

echo "This test requires tcpip to be patched with fast-start."
opam info tcpip | grep pinned && echo "Pin found. Continuing... (not checked for correct patch)" || exit -1

eval `opam config env`

sudo apt-get install hping3 coreutils avahi-utils -y

# todo: this check is not very good... should check for libxl-support, not version
VIRSH_VERSION=$(sudo virsh --version)
if [ "$VIRSH_VERSION" != "1.2.8" ]; then
    echo "Requires libvirt compiled with --with-libxl. See install script in /root/scripts/"
    exit -1
fi

# make sure libvirt is running
initctl list | grep libvirtd || exit -1
sudo start libvirtd

# kill old jitsus (if any)
sudo pkill jitsu

# install jitsu
if [ ! -d "$TEST_PATH" ]; then
        echo "Remote $TEST_PATH not found. Exiting"
        exit -1
fi

cd $TEST_PATH || exit -1
opam install lwt dns libvirt -y || exit -1
if [ -d "jitsu" ]; then
    cd jitsu && git pull && cd - || exit -1
else
    git clone https://github.com/MagnusS/jitsu.git jitsu || exit -1
fi
#cd jitsu && git checkout 0cc21d82eb741da0a885414d6822c2cf562af527 && cd - || exit -1
#curl https://raw.githubusercontent.com/MagnusS/jitsu/master/add_vif.c -o jitsu/add_vif.c
cd jitsu && git checkout cfa23339ed869fe7bac0511a2b96744de6bb381c && cd - || exit -1

echo "jitsu commit is"
cd jitsu && git rev-parse HEAD && cd -
echo "jitsu branch is"
cd jitsu && git branch && cd -

cd $TEST_PATH/jitsu && \
make && \
gcc add_vif.c -o scripts/fast-vif-bridge -O2 -Wall && \
strip scripts/fast-vif-bridge && \
cd - || \
exit -1

# setting up pins
opam pin add mirage-net-xen 1.2.0 -y -n
opam pin add tcpip 'https://github.com/samoht/mirage-tcpip#fast-start-3' -y -n
opam pin add mirage-types 'https://github.com/samoht/mirage#uip' -y # both mirage-net-xen and tcpip depends on mirage-types, so only recompile here

# make sure old unikernel is not running

# disable delays in bridge, set in "hub mode"
echo "disable stp"
sudo brctl stp br0 off
echo "set ageing 0"
sudo brctl setageing br0 0
echo "set fd 0"
sudo brctl setfd br0 0

# setup unikernel

function make_unikernel () {
	name=$1
	ip=$2
	gw=$UNIKERNEL_GW
	netmask=$UNIKERNEL_NETMASK
	mac=$3
	file=$4
	dir=$5
	mode=$6
	memory=$7

	echo "Compiling unikernel $name with ip $ip gw $gw netmask $netmask mac $mac, read from $dir, compiled to in $file, mode=$mode"

	cd $dir && \
	cat config.tmpl | \
	sed "s/\$UNIKERNEL_IP/$ip/g" | \
	sed "s/\$UNIKERNEL_GW/$gw/g" | \
	sed "s/\$UNIKERNEL_NETMASK/$netmask/g" > config.ml && \
	cat config.ml && \
	cat dispatch.tmpl | \
	sed "s/\$MODE/$mode/g" > dispatch.ml && \
	cat dispatch.ml && \
	mirage clean && \
	mirage configure --xen && \
	mirage build && \
	cp mir-www.xen $file && \
	cd .. || \
	exit -1

	echo "<domain type='xen'>
	<name>$name</name>
	<!-- low memory = faster startup -->
	<memory unit='KiB'>$memory</memory>
	<currentMemory unit='KiB'>$memory</currentMemory>
	<vcpu placement='static'>1</vcpu>
	<os>
	<type arch='armv7l' machine='xenpv'>linux</type>
	<!-- replace with kernel -->
	<kernel>$file</kernel>
	<cmdline> </cmdline>
	</os>
	<clock offset='utc' adjustment='reset'/>
	<on_poweroff>destroy</on_poweroff>
	<on_reboot>restart</on_reboot>
	<on_crash>preserve</on_crash>
	<devices>
	<interface type='bridge'>
	  <mac address='$mac'/>
	  <source bridge='br0'/>
	  <script path='$TEST_PATH/jitsu/scripts/fast-vif-bridge'/>
	</interface>
	<console type='pty'>
	  <target type='virtio' port='0'/>
	</console>
	</devices>
	</domain>" > $TEST_PATH/jitsu/jitsu_libvirt.xml

	echo "<domain type='xen'>
	<name>${name}-default</name>
	<!-- low memory = faster startup -->
	<memory unit='KiB'>$memory</memory>
	<currentMemory unit='KiB'>$memory</currentMemory>
	<vcpu placement='static'>1</vcpu>
	<os>
	<type arch='armv7l' machine='xenpv'>linux</type>
	<!-- replace with kernel -->
	<kernel>$file</kernel>
	<cmdline> </cmdline>
	</os>
	<clock offset='utc' adjustment='reset'/>
	<on_poweroff>destroy</on_poweroff>
	<on_reboot>restart</on_reboot>
	<on_crash>preserve</on_crash>
	<devices>
	<interface type='bridge'>
	  <mac address='$mac'/>
	  <source bridge='br0'/>
	</interface>
	<console type='pty'>
	  <target type='virtio' port='0'/>
	</console>
	</devices>
	</domain>" > $TEST_PATH/jitsu/jitsu_libvirt_default.xml

	sudo virsh destroy $name 2>&1 > /dev/null
	sudo xl destroy $name 2>&1 >  /dev/null
	sudo virsh undefine $name 2>&1 > /dev/null # undefine old test-unikernel if it exists
	sudo virsh define $TEST_PATH/jitsu/jitsu_libvirt.xml || exit -1 # define new kernel

	sudo virsh destroy ${name}-default 2>&1 > /dev/null
	sudo xl destroy ${name}-default 2>&1 >  /dev/null
	sudo virsh undefine ${name}-default 2>&1 > /dev/null # undefine old test-unikernel if it exists
	sudo virsh define $TEST_PATH/jitsu/jitsu_libvirt_default.xml || exit -1 # define new kernel
}


make_unikernel test-unikernel1 $UNIKERNEL_IP1 $UNIKERNEL_MAC1 $RESULT_PATH/unikernel1.xen $TEST_PATH/unikernel Normal 32000

make_unikernel test-unikernel-fast-start1 $UNIKERNEL_IP1 $UNIKERNEL_MAC1 $RESULT_PATH/unikernel-fast-start1.xen $TEST_PATH/unikernel Fast_start_app 32000

make_unikernel synjitsu $UNIKERNEL_IP5 $UNIKERNEL_MAC5 $RESULT_PATH/synjitsu.xen $TEST_PATH/synjitsu Normal 64000

# Remove ip from xenstore, just in case
sudo xenstore-rm /ip

# disabling remote cron
sudo service cron stop
