#!/bin/bash

echo "This script is executed locally before the tests"

echo "Set /dev/bpf* o+r to allow tcpdump from ordinary user. This is reset on reboot. Requires sudo:"
sudo chmod o+r /dev/bpf*

which pip && \
    pip list | grep dnspython && \
    echo "dnspython installed" || \
    (echo "Installing dnspython with pip (requires sudo)" && \
    sudo pip install dnspython)

which apt-get && \
    sudo apt-get install python-dnspython

sudo arp -s $UNIKERNEL_IP1 $UNIKERNEL_MAC1
sudo arp -s $UNIKERNEL_IP2 $UNIKERNEL_MAC2
sudo arp -s $UNIKERNEL_IP3 $UNIKERNEL_MAC3
sudo arp -s $UNIKERNEL_IP4 $UNIKERNEL_MAC4
sudo arp -s $UNIKERNEL_IP5 $UNIKERNEL_MAC5
