#!/bin/bash

TEST_PATH=$(dirname $0)

MIRAGE_VER=2.0.0
echo "This test requires $MIRAGE_VER"
opam list mirage | grep $MIRAGE_VER && echo "Mirage $MIRAGE_VER found" || exit -1
eval `opam config env`

sudo apt-get install hping3 coreutils -y

cd $TEST_PATH/unikernel && \
cat config.tmpl | \
sed "s/\$UNIKERNEL_IP1/$UNIKERNEL_IP1/g" | \
sed "s/\$UNIKERNEL_IP2/$UNIKERNEL_IP2/g" | \
sed "s/\$UNIKERNEL_IP3/$UNIKERNEL_IP3/g" | \
sed "s/\$UNIKERNEL_IP4/$UNIKERNEL_IP4/g" | \
sed "s/\$UNIKERNEL_IP5/$UNIKERNEL_IP5/g" | \
sed "s/\$UNIKERNEL_GW/$UNIKERNEL_GW/g" | \
sed "s/\$UNIKERNEL_NETMASK/$UNIKERNEL_NETMASK/g" > config.ml && \
mirage clean && \
mirage configure --xen && \
cat Makefile | sed "s#-lbigarray#-lbigarray -L/usr/lib/arm-linux-gnueabihf#g" > Makefile.2 && \
mv Makefile.2 Makefile && \
mirage build && \
cd .. || \
exit -1

unikernel=$(pwd)/unikernel/mir-www.xen

echo "name = 'test-unikernel'
kernel = '$unikernel'
builder = 'linux'
memory = 16
on_crash = 'preserve'
vif = [ 'mac=${UNIKERNEL_MAC1},bridge=br0' ]" >> unikernel.xl

sudo xl destroy test-unikernel
sudo xl create unikernel.xl
