#!/bin/bash

TEST_PATH=$(dirname $0)
python $TEST_PATH/read_files.py > results.dat && \
cat results.dat && \
cat results.dat | sort -k 5 -n | grep -v openmirage | grep -v google | sed "s/$LINUX_GUEST_IP/linux_guest/g" | sed "s/$UNIKERNEL_IP1/mirage_guest/g" | sed "s/$UNIKERNEL_GW/local_network/g" | python $TEST_PATH/plot.py
