#!/bin/bash

TEST_PATH=$(dirname $0)
export

eval `opam config env`

#MIRAGE_VER=2.0.0
#opam list mirage | grep $MIRAGE_VER && echo "Mirage $MIRAGE_VER found" || echo "Mirage = $MIRAGE_VER required" && exit -1
opam list mirage | grep mirage && echo "Mirage found" || exit -1

sudo apt-get install hping3 coreutils -y

cd $TEST_PATH/unikernel && \
mirage clean && \
mirage configure --xen && \
cat Makefile | sed "s#-lbigarray#-lbigarray -L/usr/lib/arm-linux-gnueabihf#g" > Makefile.2 && \
mv Makefile.2 Makefile && \
mirage build && \
cd .. || \
exit -1

